name: SphinxDocumentation

on: [push, pull_request]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: install ubuntu dependencies
        run: |
          sudo apt-get install pandoc freeglut3 libglew-dev
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser nbsphinx robotic numpy
      - name: Sphinx build
        run: |
          sphinx-build doc build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
          force_orphan: true
